typography_spectrum: 0.15186492167413235
color:
  brandStrength: 0.14432742772623897
  lightness: 0.08860269654542208
  saturation: 0.3630153809208423
  rhythmicContrast: 0.03322858875617385
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
layout_spectrum: 0.6914087950717658
author:
  name: Benjy
  email: benjysingh@gamail.com
  url: 'https://thegrid.ai/awesome-gfv60/'
name: awesome
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/804d1b27-816a-42f6-91ff-e7c65fc68f71.jpg
title: ' Welcome !!!'
description: Enjoy
